<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions targetNamespace="http://www.ibm.com/wbsexmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://www.ibm.com/wbsexmlns:intf="http://www.ibm.com/wbse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><wsdl:message name="demandedService"><wsdl:part name="demandedService" type="xs:string" /></wsdl:message><wsdl:message name="returnService"><wsdl:part name="returnService" type="xs:string" /></wsdl:message><wsdl:portType name="ProcessDemandingRequest"><wsdl:operation name="process"><wsdl:input message="demandedService" /><wsdl:output message="returnService" /></wsdl:operation></wsdl:portType><wsdl:service name="FLYPEER://FLYPEER-DOCUMENTS-ON-OFFER"><wsdl:documentation>Documents On Offer Service</wsdl:documentation></wsdl:service></wsdl:definitions>